nginx:
    image: nginx
    volumes:
        - /home/test/qduoj/OnlineJudge/dockerfiles/oj_web_server/oj.conf:/etc/nginx/conf.d/default.conf
        - /home/test/qduoj/upload:/home/upload
        - /home/test/qduoj/OnlineJudge/:/home/OnlineJudge
    links:
         - oj_web_server:oj_web_server
    ports:
        - "0.0.0.0:80:80"
